package com.exceptions;

import java.util.ArrayList;
import java.util.List;
import java.util.ListIterator;
import java.util.Scanner;

public class Exception1 {

	
	public static void main(String[] args) {
		
		int a = 10; 
		int b = 0;
//		Arithmetic Exception	
//		System.out.println(a/b);	//invalid arithmetic operation
	
//		IndexOutOfBound Exception
//		List<Integer> l = new ArrayList<Integer>();
//		l.add(10);
//		System.out.println(l.get(1));	//searching for data out of the array list size

//		ArrayIndexOutOfBounds Exception
//		int [] a1 = new int [5]; 	//searching for data out of the size of array
//		System.out.println(a1[10]);
		
//		StringIndexOutOfBound Exception
//		String s = "Michael"; 	//searching for character out of string size
//		System.out.println(s.charAt(10));
		
//		NullPointer Exception
//		String s1 = null; 	 //Searching for character inside string whose value is null
//		System.out.println(s1.charAt(0));
		
//		NumberFormat Exception
//		String s2 = "ABC123";
//		int a2 = Integer.parseInt(s2); 	//Cant parse/convert to number since having "ABC" in the string
//		System.out.println(a2);
		
//		InputMismatch Exception
//		Scanner s3 = new Scanner(System.in);
//		System.out.println("Enter the value");
//		int nextint = s3.nextInt(); 	//Give input as string not a number
//		System.out.println(nextint);
		
	}
}
